/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-container": "#00174b",
        "outline": "#76777d",
        "tertiary-fixed-dim": "#4edea3",
        "secondary-fixed": "#d3e4fe",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed": "#002113",
        "on-secondary-fixed-variant": "#38485d",
        "inverse-surface": "#2d3133",
        "on-primary-fixed": "#00174b",
        "outline-variant": "#c6c6cd",
        "error": "#ba1a1a",
        "background": "#f7f9fb",
        "surface-variant": "#e0e3e5",
        "on-secondary-container": "#54647a",
        "surface-container-lowest": "#ffffff",
        "surface-tint": "#0053db",
        "on-surface": "#191c1e",
        "inverse-primary": "#b4c5ff",
        "on-error": "#ffffff",
        "on-tertiary-container": "#009668",
        "inverse-on-surface": "#eff1f3",
        "surface-container-highest": "#e0e3e5",
        "on-primary": "#ffffff",
        "surface-dim": "#d8dadc",
        "on-error-container": "#93000a",
        "secondary-fixed-dim": "#b7c8e1",
        "primary": "#000000",
        "on-surface-variant": "#45464d",
        "error-container": "#ffdad6",
        "secondary-container": "#d0e1fb",
        "tertiary-container": "#002113",
        "primary-fixed": "#dbe1ff",
        "on-tertiary-fixed-variant": "#005236",
        "surface-container-high": "#e6e8ea",
        "surface": "#f7f9fb",
        "on-tertiary": "#ffffff",
        "on-background": "#191c1e",
        "secondary": "#505f76",
        "on-primary-container": "#497cff",
        "on-secondary-fixed": "#0b1c30",
        "tertiary": "#000000",
        "on-primary-fixed-variant": "#003ea8",
        "tertiary-fixed": "#6ffbbe",
        "primary-fixed-dim": "#b4c5ff",
        "surface-bright": "#f7f9fb",
        "surface-container": "#eceef0",
        "surface-container-low": "#f2f4f6"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"
      },
    },
  },
  plugins: [],
};
